[package]
name = "river"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "river"
path = "src/main.rs"

[dependencies]
crossterm = "0.28"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5.0"
chrono = "0.4"