# River Editor Configuration

# Enable vim keybindings (true/false)
# When true: Uses vim modes (Normal, Insert, Command) with vim keybindings
# When false: Uses standard editor keybindings (always in insert mode)
vim_bindings = false

# Tab size (number of spaces for tab key)
tab_size = 4

# Directory where daily notes are stored
# Default: ~/Documents/DailyNotes
daily_notes_dir = "~/river/notes"

# Typing timeout in seconds (how long before typing session ends)
# Default: 180 (3 minutes)
typing_timeout_seconds = 180

# Enable writing prompts (true/false)
# Default: true
show_prompts = true

# Prompt display style: "ghost", "none", or "command_only"
# - ghost: Shows prompt as gray text that disappears on first keystroke
# - none: No prompts displayed
# - command_only: Only accessible via :prompt command
# Default: "ghost"
prompt_style = "ghost"

# Use AI-generated prompts based on your journal history
# Requires ANTHROPIC_API_KEY environment variable
# Run "river --generate-prompts" to create personalized prompts
# Default: true
use_ai_prompts = true
