# River Editor Configuration

# Enable vim keybindings (true/false)
# When true: Uses vim modes (Normal, Insert, Command) with vim keybindings
# When false: Uses standard editor keybindings (always in insert mode)
vim_bindings = false

# Tab size (number of spaces for tab key)
tab_size = 4

# Directory where daily notes are stored
# Default: ~/Documents/DailyNotes
daily_notes_dir = "~/river/notes"